### ISSUE TITLE
js sourcecode

### ISSUE THREAD

**Issue by calmking** [aaronchen2k/mobistore#1]
Can u provide whole project sourcecode? Thank you very much!

**Comment by aaronchen2k** [comment]
You may find all codes in mobistore-client and mobistore-web project

**Comment by calmking** [comment]
I use client ,but cannot find js code in this project . And I cannot run the client. Can you show me how to use ? Thanks. The web is the back end。

**Comment by calmking** [comment]
I realy like your code. I‘m dying to learn it.

**Comment by aaronchen2k** [comment]
Client codes is in mobistore-client/app folder, you need to run "ionic serve" command to compile and launch the webclient in browser.
Please refer to http://ionicframework.com/docs/v2/getting-started/installation

**Comment by calmking** [comment]
I run "ionic serve", but the browser is blank.

**Comment by calmking** [comment]
I have sent a QQ message to you . Can we talk by QQ?
