### ISSUE TITLE
Ionic v1 does not work on IOS simulator/device

### ISSUE THREAD

**Issue by mxiamxia** [aaronchen2k/mobistore#2]
Hi, I am trying to run ionic v1 of your app. It is working with ionic serve, but when I ran it on IOS 9 simulator. it gave blank screen and the debugger console shows all the html pages/resources from router can not be found. Can you help to make it work in IOS simulator?

**Comment by aaronchen2k** [comment]
Maybe it's a path issue, could you please send the console log to us?
